name: BMP CI
on: { push: { branches: [main] } }

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with: { go-version: '1.22' }
    - run: go test ./...
    - run: docker build -t bmp:${{ github.sha }} . 